spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  mail:
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"

mail-custom:
  health-check-enabled: false

management:
  endpoint:
    health:
      exclude: mail

logging:
  level:
    root: INFO
    com.shivamingale.invoice: DEBUG
