spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
server:
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never
  http2:
    enabled: true

logging:
  level:
    root: WARN
    com.shivamingale.invoice: INFO
    org.springframework: WARN
    org.hibernate: WARN
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}","level":"%level","logger":"%logger{36}","message":"%msg","thread":"%thread"}%n'

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
  health:
    db:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99

invoice:
  sequence-cache-size: 1000
