spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
mail-custom:
  health-check-enabled: true
server:
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never

cookie:
  secure: false
  same-site: Lax

logging:
  level:
    root: INFO
    com.shivamingale.invoice: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
