spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    h2:
    console:
      enabled: true
  mail:
    properties:
      mail:
        smtp:
          starttls:
            require: false
          ssl:
            trust: "*"
  mail-custom:
    health-check-enabled: true

server:
  error:
    include-message: always
    include-stacktrace: always
    include-binding-errors: always

cookie:
  secure: false
  same-site: Lax

logging:
  level:
    root: DEBUG
    com.shivamingale.ecom: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
